<?php

namespace App\Controller\Admin;

use App\Entity\Genre;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class GenreCrudController extends AbstractCrudController
{

    public function index(AdminContext $context)
    {
        return parent::index($context); // TODO: Change the autogenerated stub
    }

    public static function getEntityFqcn(): string
    {
        return Genre::class;
    }

    public function createEntity(string $entityFqcn)
    {
        $genre = new Genre();
        $genre->setAdmin($this->getUser());
        $genre->setCreatedAt(new \DateTimeImmutable());
        return $genre;
    }

    public function configureFields(string $pageName): iterable
    {
        $res = [
            TextField::new('name')
        ];
        if ($pageName === Crud::PAGE_EDIT || $pageName === Crud::PAGE_NEW) {
            $res[] = AssociationField::new('applications')->setDisabled();
            return $res;
        }
        $res[] = AssociationField::new('admin');
        $res[] = DateTimeField::new('createdAt');
        $res[] = AssociationField::new('applications')->setDisabled();
        return $res;
    }

    public function configureActions(Actions $actions): Actions
    {
        return $actions
            ->add(Crud::PAGE_INDEX, Action::new('detail', 'Detail')
                ->linkToCrudAction(Crud::PAGE_DETAIL));
    }
}
